#!/usr/bin/env python3

# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

"""IRIS artifact server: serve the agent bundle + per-device install files over
HTTPS. Mirrors catalog.py's exact stdlib TLS pattern (ThreadingHTTPServer +
SSLContext(PROTOCOL_TLS_SERVER) + load_cert_chain(IRIS_CERT) + wrap_socket),
reusing the SAME combined cert (IRIS_CERT) the catalog already serves with, but on
its own port (IRIS_ARTIFACTS_PORT, default 8000; the catalog defaults to 8443). The
only differences from the catalog are the request handler (static files from the
artifacts dir) and the port. Staging URLs use high-entropy filename capabilities
generated by the installer; TLS protects those capabilities in transit while the
operator's existing SSH session delivers the fetch command to the device. Stdlib
only."""
import os
import ssl
import time
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer

# Subdirectory (relative to the artifacts root) that holds per-device staging
# configs.  Files under this prefix are swept lazily after STAGING_MAX_AGE_SECONDS
# rather than deleted immediately after the first GET.  This lets device-install.sh
# retry 'copy https://' up to 3 times (with 10 s sleeps) within the install window
# if the SSH pipe drops the first transfer's output — while still bounding how long
# per-device credentials are reachable from the network.
_STAGING_PREFIX = "staging" + os.sep

# How long (seconds) a staging file is retained after creation.  Must be long
# enough for device-install.sh's 3-attempt retry loop (2 × 10 s sleep = at least
# 20 s needed; 600 s gives ample headroom for SSH reconnects and slow IOS copies).
STAGING_MAX_AGE_SECONDS = 600


def sweep_staging(directory, now=None):
    """Delete staging/ files whose mtime is older than STAGING_MAX_AGE_SECONDS.

    Called lazily on each incoming GET for a staging path so no background
    thread is needed.  Ignores errors (e.g. concurrent deletion by another
    process) so it never raises.
    """
    if now is None:
        now = time.time()
    staging_dir = os.path.join(directory, "staging")
    try:
        entries = os.listdir(staging_dir)
    except OSError:
        return
    cutoff = now - STAGING_MAX_AGE_SECONDS
    for name in entries:
        path = os.path.join(staging_dir, name)
        try:
            if os.path.isfile(path) and os.path.getmtime(path) < cutoff:
                os.unlink(path)
        except OSError:
            pass


def secure_staging_permissions(directory):
    """Restrict existing credential files before they can be served.

    Same contract as the request-time check in do_GET: files staged from
    OUTSIDE this container (remote SSH staging, or a stage-host-local CLI
    run) are owned by a foreign uid, so chmod by this process always raises
    EPERM even though the installer wrote them with umask 077. What matters
    is the file's actual permission bits — a foreign-owned file whose mode is
    already tight stays; only a LOOSE file that cannot be tightened is
    removed. Deleting on every chmod failure would destroy valid staged
    credentials at server start."""
    staging_dir = os.path.join(directory, "staging")
    try:
        entries = os.listdir(staging_dir)
    except OSError:
        return
    for name in entries:
        path = os.path.join(staging_dir, name)
        try:
            if not os.path.isfile(path):
                continue
            st = os.stat(path)
        except OSError:
            # Cannot even stat it — fail closed rather than serve unknown
            # permissions later.
            try:
                os.unlink(path)
            except OSError:
                pass
            continue
        mode_already_tight = (st.st_mode & 0o077) == 0
        try:
            os.chmod(path, 0o600)
        except OSError:
            if mode_already_tight:
                continue
            # A loose credential file whose permissions cannot be restricted
            # must not remain available to either local users or HTTP
            # clients.
            try:
                os.unlink(path)
            except OSError:
                pass


def make_server(host, port, directory, certfile=None):
    class Handler(SimpleHTTPRequestHandler):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, directory=directory, **kwargs)

        def list_directory(self, path):
            """Directory listing disabled — 404 on all directory requests."""
            self.send_error(404, "Not Found")
            return None

        def do_GET(self):
            """Serve the file; lazily sweep expired staging files."""
            resolved = self.translate_path(self.path)
            # Sweep staging/ for expired files before serving — this limits
            # credential exposure without breaking retries within the window.
            if (os.path.isfile(resolved) and
                    os.path.relpath(resolved, directory).startswith(
                        _STAGING_PREFIX)):
                # Files staged from OUTSIDE this container (remote SSH
                # staging, or a stage-host-local CLI run) are owned by a
                # foreign uid: chmod by a non-owner always raises EPERM, even
                # though the installer wrote the file with umask 077 (already
                # group/other-inaccessible). What matters is the file's
                # actual permission bits, not whether THIS process can
                # tighten them — so only attempt the chmod when we own the
                # file, and only fail closed when the mode is actually loose.
                try:
                    st = os.stat(resolved)
                except OSError:
                    self.send_error(403, "Staging file permissions are unsafe")
                    return
                mode_already_tight = (st.st_mode & 0o077) == 0
                if os.geteuid() == st.st_uid:
                    # Co-located path: the installer (this process's own uid)
                    # created the file, so enforce least-privilege immediately
                    # before this process reads it — unchanged behavior. A
                    # chmod failure only fails the request when the mode is
                    # actually loose; if it's already tight the security
                    # property holds regardless of why the chmod failed.
                    try:
                        os.chmod(resolved, 0o600)
                    except OSError:
                        if not mode_already_tight:
                            self.send_error(
                                403, "Staging file permissions are unsafe")
                            return
                elif not mode_already_tight:
                    # Foreign-owned (e.g. staged via remote SSH or a
                    # stage-host-local CLI run) and group/other-accessible:
                    # we cannot chmod a file we don't own, and the loose mode
                    # is unsafe, so fail closed.
                    self.send_error(403, "Staging file permissions are unsafe")
                    return
                # else: foreign-owned but already mode-tight (installers
                # write with umask 077) — acceptable as-is, no chmod
                # attempted. If this uid still can't read it, that surfaces
                # as its own read failure below rather than a gratuitous 403
                # here.
                sweep_staging(directory)
            super().do_GET()

        def log_message(self, *args):
            pass

    secure_staging_permissions(directory)
    srv = ThreadingHTTPServer((host, port), Handler)
    if certfile:
        ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        ctx.load_cert_chain(certfile)
        srv.socket = ctx.wrap_socket(srv.socket, server_side=True)
    return srv


def main():
    host = os.environ.get("IRIS_ARTIFACTS_HOST", "0.0.0.0")
    port = int(os.environ.get("IRIS_ARTIFACTS_PORT", "8000"))
    directory = os.environ.get("IRIS_ARTIFACTS_DIR", "/srv/artifacts")
    cert = os.environ.get("IRIS_CERT", "/etc/iris/tls/cert.pem")
    certfile = cert if os.path.exists(cert) else None
    srv = make_server(host, port, directory, certfile=certfile)
    scheme = "https" if certfile else "http"
    print("artifacts on %s://%s:%d (dir %s)" % (scheme, host, port, directory),
          flush=True)
    srv.serve_forever()


if __name__ == "__main__":
    main()
