#!/usr/bin/env python3

# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gui_admin import main
sys.exit(main())
