#!/usr/bin/env python3
# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

"""Terminal helper for IRIS signing and recovery keys."""

from iris_installer.key_setup import main

if __name__ == "__main__":
    raise SystemExit(main())
