#!/usr/bin/env python3
# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

"""Private local OpenSSH passphrase dialog; invoked only by ssh-keygen."""

from iris_installer.custody_gui import askpass

if __name__ == "__main__":
    raise SystemExit(askpass())
