#!/usr/bin/env python3
# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

"""Development entry point for shared installer components."""

from iris_installer.cli import main

if __name__ == "__main__":
    raise SystemExit(main())
